version: "3.8"

services:
  mysql1:
    image: mysql-with-seed
    container_name: cluster-1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "4000:3306" # Lắng nghe trên port 4000

  mysql2:
    image: mysql-with-seed
    container_name: cluster-2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "4001:3306" # Lắng nghe trên port 4001
